apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prom-kube-prometheus-prometheus
  ports:
    - name: web
      port: 9091
      targetPort: 9090
      protocol: TCP
---
# Port forward service for easy access
apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prom-kube-prometheus-prometheus
  ports:
    - name: web
      port: 9091
      targetPort: 9090
      nodePort: 30090
      protocol: TCP