apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load
  namespace: default
  labels:
    app: k6-load
spec:
  template:
    metadata:
      labels:
        app: k6-load
    spec:
      containers:
        - name: k6
          image: dhruvre/k6-loadtest:latest
          command: ["k6", "run", "./loadtest.js"]
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
          env:
            - name: TARGET
              value: "http://flask-load.monitoring.svc.cluster.local:5051/burn?seconds=3&work=1"
            - name: K6_OUT
              value: "json=/tmp/k6-results.json"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts
      restartPolicy: Never
  backoffLimit: 2