apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-load
  namespace: monitoring
  labels:
    app: flask-load
    release: kube-prom  # This label helps Prometheus find this ServiceMonitor
spec:
  selector:
    matchLabels:
      app: flask-load
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - monitoring